// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcwvpxmsxnhhvsqwjkuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjd3ZweG1zeG5oaHZzcXdqa3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NTg4NTIsImV4cCI6MjA3NzAzNDg1Mn0.OL25ps2BpXqX43KR5ASWSZGM5TT7IC56QfOy7Pl1Mqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});